Update stylelint to use stylelint-order
ArcBees/frontend-style-guide pull request #5
Opened 2017-08-11 14:42 UTC by jasonlemay

Now using `stylelint-order` instead of the deprecated `declaration-block-properties-order`.

Also, removed deprecated rules : 
- declaration-block-no-ignored-properties
- media-feature-no-missing-punctuation
- root-no-standard-properties
- rule-nested-empty-line-before
- rule-non-nested-empty-line-before
- selector-max-compound-selectors
- selector-no-empty

2017-08-11 19:24 UTC, jni- approved these changes

2017-08-11 19:34 UTC, Chris-V requested changes

2017-08-11 19:34 UTC, Chris-V commented on .stylelintrc
> +    order/properties-order: [
Tu devrais prendres l'habitude de quoter toutes tes keys. Pas certain que celle là est du json valide sans les quotes.

2017-08-11 19:34 UTC, Chris-V commented on .stylelintrc
>      declaration-block-no-duplicate-properties: [true, ignore: "consecutive-duplicates-with-different-values"],
ignore: "" devrais être entre curlies

2017-08-21 13:43 UTC, jasonlemay commented on .stylelintrc
>      declaration-block-no-duplicate-properties: [true, ignore: "consecutive-duplicates-with-different-values"],
Done!

2017-08-21 13:43 UTC, jasonlemay commented on .stylelintrc
> +    order/properties-order: [
Done!

2017-08-21 13:47 UTC, merged